spring:
  application:
    name: "auth-server"
  security:
    oauth2:
      authorizationserver:
        client:
          gateway-client:
            registration:
              client-id: "gateway-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/gateway-client"
                - "http://localhost:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
server:
  port: 9000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE