spring:
  application:
    name: "gateway"
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: "spring"
            client-name: "gateway"
            client-id: "gateway-client"
            client-secret: "secret"
            scope:
              - "openid"
              - "profile"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
          recipes-service:
            client-name: "Recipes Service"
            client-id: "recipes-service"
            client-secret: "recipes"
            provider: "spring"
            scope:
              - "recipes:read"
              - "recipes:write"
            redirect-uri: "{baseUrl}/authorize/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "urn:ietf:params:oauth:grant-type:token-exchange"
          ticket-service:
            client-name: "Ticket Service"
            client-id: "ticket-service"
            client-secret: "ticket"
            provider: "spring"
            scope:
              - "ticket:read"
              - "ticket:write"
            redirect-uri: "{baseUrl}/authorize/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "urn:ietf:params:oauth:grant-type:token-exchange"
        provider:
          spring:
            issuer-uri: "http://localhost:9000"
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: "recipes"
          uri: "http://localhost:8089"
          predicates:
            - Path=/api/recipes/**
            - Header=Netcas-Agent,DESS-Angular
          filters:
            - TokenRelay=recipes-service
        - id: "tickets"
          uri: "http://localhost:8088"
          predicates:
            - Path=/api/ticket/**
            - Header=Netcas-Agent,DESS-Angular
          filters:
            - TokenRelay=ticket-service
        - id: "angular"
          uri: "http://localhost:4200"
          predicates:
            - Path=/angular-ui/**,/assets/**
        - id: "userInfo"
          uri: "http://localhost:9000"
          predicates:
            - Path=/userinfo
            - Header=Netcas-Agent,DESS-Angular
          filters:
            - TokenRelay=

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE