spring:
  application:
    name: "gateway"
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: "spring"
            client-name: "gateway"
            client-id: "gateway-client"
            client-secret: "secret"
            scope:
              - "openid"
              - "profile"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
        provider:
          spring:
            issuer-uri: "http://localhost:9000"
  cloud:
    gateway:
      routes:
        - id: "recipes"
          uri: "http://localhost:8089"
          predicates:
            - Path=/api/recipes/**
          filters:
            - TokenRelay=
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE